# 7/14/2022: As of v1.1.0, scikit-learn requires minimum of numpy 1.17.3. 
# See https://scikit-learn.org/dev/whats_new/v1.1.html#version-1-1-0
numpy:
  # python 3.7-3.9
  - 1.19    # [not (osx and arm64)]
  - 1.19    # [not (osx and arm64)]
  - 1.19    # [not (osx and arm64)]
  # python 3.8-3.9
  - 1.19    # [osx and arm64]
  - 1.19    # [osx and arm64]
  # python 3.10
  - 1.21
python:
  - 3.7      # [not arm64]
  - 3.8
  - 3.9
  - 3.10
zip_keys:
  -
    - python
    - numpy
