{% set version = "0.24.2" %}

package:
  name: scikit-learn
  version: {{ version }}

source:
  url: https://github.com/scikit-learn/scikit-learn/archive/{{ version }}.tar.gz
  sha256: 642fb016bfe4bb7539ba6bf4e6dd5a95d2d25638387040b0f5eefdb84a840297

build:
  number: 2
  script: python -m pip install --no-deps --ignore-installed .  --verbose
  skip: True  # [py<35]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
  host:
    - python
    - pip
    - llvm-openmp  # [osx]
    - cython >=0.28.5
    - numpy
    - scipy >=0.19.1
    - joblib >=0.11
    - threadpoolctl >=2.0.0
  run:
    - python
    - llvm-openmp  # [osx]
    - {{ pin_compatible('numpy') }}
    - scipy >=0.19.1
    - joblib >=0.11
    - threadpoolctl >=2.0.0
    # Using selector until packages for other platforms are (re)built using
    # newer defaults toolchains that use the `_openmp_mutex` mechanism.
    - _openmp_mutex   # [s390x]


# Some tests take alot of memory, and seem to cause segfaults when memory runs out
{% set test_cpus = 1 %}

{% set tests_to_skip = "_not_a_real_test" %}
# https://github.com/scikit-learn/scikit-learn/issues/20335
{% set tests_to_skip = tests_to_skip + " or test_loadings_converges" %}
# Can fail on aarch64 -- https://github.com/scikit-learn/scikit-learn/issues/15821
{% set tests_to_skip = tests_to_skip + " or test_uniform_grid" %}                         # [aarch64]
# Can fail -- https://github.com/scikit-learn/scikit-learn/issues/15818
{% set tests_to_skip = tests_to_skip + " or test_sag_regressor_computed_correct" %}       # [linux]
# Occasionally fails on aarch64 -- https://github.com/scikit-learn/scikit-learn/issues/15825
{% set tests_to_skip = tests_to_skip + " or test_unreachable_accuracy" %}                 # [aarch64]
# Fails on linux-aarch64
{% set tests_to_skip = tests_to_skip + " or test_np_matrix" %}                  # [linux and aarch64]
{% set tests_to_skip = tests_to_skip + " or test_lle_simple_grid" %}            # [linux and aarch64]
# skip network tests -- https://github.com/scikit-learn/scikit-learn/issues/16743
{% set tests_to_skip = tests_to_skip + " or network" %}
{% set tests_to_skip = tests_to_skip + " or test_california_housing" %}
# ppc64le failing test
{% set tests_to_skip = tests_to_skip + " or test_k_means" %}  # [ppc64le]
{% set tests_to_skip = tests_to_skip + " or test_mlp_regressor_dtypes_casting" %}  # [ppc64le]

{% set tests_to_skip = tests_to_skip + " or test_precomputed_nearest_neighbors_filtering" %}          # [win32]
{% set tests_to_skip = tests_to_skip + " or test_pca_n_components_mostly_explained_variance_ratio" %} # [win32]
{% set tests_to_skip = tests_to_skip + " or (GaussianProcessRegressor and check_supervised_y_2d)" %}  # [win32]
{% set tests_to_skip = tests_to_skip + " or (GaussianProcessRegressor and check_fit_idempotent)" %}   # [win32]
{% set tests_to_skip = tests_to_skip + " or (SpectralEmbedding and check_pipeline_consistency)" %}    # [win32]
{% set tests_to_skip = tests_to_skip + " or (Nystroem and check_fit_idempotent)" %}                   # [win32]

test:
  requires:
    - pytest >=3.3.0
    - cython >=0.28.5
    - pytest-xdist
    - pytest-timeout
    - pip
  imports:
    - sklearn
  commands:
    - set OPENBLAS_NUM_THREADS=1          # [win]
    - set OMP_NUM_THREADS=1               # [win]
    - export OPENBLAS_NUM_THREADS=1       # [not win]
    - export OMP_NUM_THREADS=1            # [not win]
    - pytest --timeout 300 -n {{ test_cpus }} --verbose --pyargs sklearn -k "not ({{ tests_to_skip }})"

about:
  home: http://scikit-learn.org/
  license: BSD-3-Clause
  license_file: COPYING
  summary: A set of python modules for machine learning and data mining

extra:
  recipe-maintainers:
    - amueller
    - astaric
    - jakirkham
    - ogrisel
    - ocefpaf
    - lesteve
    - msarahan
    - jnothman
    - rth
    - adrinjalali
