{% set version = "1.0.2" %}

package:
  name: scikit-learn
  version: {{ version }}

source:
  url: https://github.com/scikit-learn/scikit-learn/archive/{{ version }}.tar.gz
  sha256: 34471662f0e5ba8d2c799391338c6f976680cc66b715e00db0c7589f4f371bc4

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .  --verbose
  skip: true  # [py<37]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
  host:
    - python
    - cython >=0.29.24
    - joblib >=0.11
    - llvm-openmp  # [osx]
    - numpy
    - pip
    - scipy >=1.1.0
    - setuptools <60.0
    - threadpoolctl >=2.0.0
    - wheel
  run:
    - python
    - joblib >=0.11
    - llvm-openmp  # [osx]
    - {{ pin_compatible('numpy') }}
    - scipy >=1.1.0
    - threadpoolctl >=2.0.0
    # Using selector until packages for other platforms are (re)built using
    # newer defaults toolchains that use the `_openmp_mutex` mechanism.
    - _openmp_mutex   # [linux and (not ppc64le)]

# Some tests take alot of memory, and seem to cause segfaults when memory runs out
{% set test_cpus = 1 %}

{% set tests_to_skip = "_not_a_real_test" %}
# https://github.com/scikit-learn/scikit-learn/issues/20335
{% set tests_to_skip = tests_to_skip + " or test_loadings_converges" %}
# Numerically unstable test numerical difference in test
{% set tests_to_skip = tests_to_skip + " or test_mlp_regressor_dtypes_casting" %}         # [ppc64le]

test:
  requires:
    - pytest >=5.0.1
    - cython >=0.29.24
    - pytest-xdist
    - pytest-timeout
  imports:
    - sklearn
  commands:
    - set OPENBLAS_NUM_THREADS=1          # [win]
    - set OMP_NUM_THREADS=1               # [win]
    - export OPENBLAS_NUM_THREADS=1       # [not win]
    - export OMP_NUM_THREADS=1            # [not win]
    - pytest --timeout 300 -n {{ test_cpus }} --verbose --pyargs sklearn -k "not ({{ tests_to_skip }})"

about:
  home: http://scikit-learn.org/
  license: BSD-3-Clause
  license_file: COPYING
  license_family: BSD
  summary: A set of python modules for machine learning and data mining
  doc_url: https://scikit-learn.org/dev/user_guide.html
  dev_url: https://github.com/scikit-learn/scikit-learn

extra:
  recipe-maintainers:
    - amueller
    - astaric
    - jakirkham
    - ogrisel
    - ocefpaf
    - lesteve
    - jnothman
    - rth
    - adrinjalali
    - glemaitre
    - jeremiedbb