{% set version = "0.19.2" %}
{% set variant = "openblas" %}

package:
  name: scikit-learn
  version: {{ version }}

source:
  # testing latest commit on the 0.19.X branch prior to 0.19.2 release
  url: https://github.com/scikit-learn/scikit-learn/archive/baa18eea47ae013c1b34fdea08e3806f0b71d9ea.tar.gz
  sha256: 2947f531ad52e81b2436b26608d8198778ac0b4baa7d2925db8b3b3fcb39c8a2

build:
  number: 0
  # We lack openblas on Windows, and therefore can't build numpy there either currently.
  skip: true  # [win]
  features:
    - blas_{{ variant }}

requirements:
  build:
    - python
    - cython
    - setuptools
    - blas 1.1 {{ variant }}
    - openblas 0.2.20|0.2.20.*
    - numpy 1.9.*  # [not (win and py36)]
    - numpy 1.11.*  # [win and py36]
    - scipy
    - nose
  run:
    - python
    - blas 1.1 {{ variant }}
    - openblas 0.2.20|0.2.20.*
    - numpy >=1.9  # [not (win and py36)]
    - numpy >=1.11  # [win and py36]
    - scipy

test:
  requires:
    - nose
  imports:
    - sklearn
  commands:
    - nosetests sklearn --exe
    - conda inspect linkages -p $PREFIX scikit-learn  # [not win]
    - conda inspect objects -p $PREFIX scikit-learn  # [osx]

about:
  home: http://scikit-learn.org/
  license: BSD 3-Clause
  license_file: COPYING
  summary: A set of python modules for machine learning and data mining

extra:
  recipe-maintainers:
    - amueller
    - astaric
    - jakirkham
    - ogrisel
    - ocefpaf
    - lesteve
