{% set name = "scikit-learn" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 84ad05fbb8529856645344a81b01a0bbff8818493535de08a5e85b2054adc31a

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .  -vv
  skip: true  # [py<38]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp    # [osx]
  host:
    - python
    - cython
    - joblib
    - llvm-openmp    # [osx]
    - numpy   1.19   # [py<310]
    - numpy   1.21   # [py==310]
    - numpy   1.23   # [py>=311]
    - pip
    - scipy
    - setuptools <60.0
    - threadpoolctl
    - wheel
  run:
    - python
    - joblib >=1.1.1
    - llvm-openmp    # [osx]
    - {{ pin_compatible('numpy') }}
    - scipy >=1.3.2
    - threadpoolctl >=2.0.0
    - _openmp_mutex  # [linux]

# Some tests take alot of memory, and seem to cause segfaults when memory runs out
{% set test_cpus = 1 %}

{% set tests_to_skip = "_not_a_real_test" %}
# https://github.com/scikit-learn/scikit-learn/issues/20335
{% set tests_to_skip = tests_to_skip + " or test_loadings_converges" %}
# Numerically unstable test numerical difference in test
{% set tests_to_skip = tests_to_skip + " or test_mlp_regressor_dtypes_casting" %}         # [ppc64le]

test:
  requires:
    - pytest >=5.3.1
    - cython >=0.29.24
    - pytest-xdist
    - pytest-timeout
    - pip
  imports:
    - sklearn
    - sklearn.cluster
    - sklearn.datasets
    - sklearn.decomposition
    - sklearn.ensemble
    - sklearn.feature_extraction
    - sklearn.linear_model
    - sklearn.manifold
    - sklearn.metrics
    - sklearn.neighbors
    - sklearn.tree
    - sklearn.utils
    - sklearn.svm
  commands:
    - pip check
    - set OPENBLAS_NUM_THREADS=1          # [win]
    - set OMP_NUM_THREADS=1               # [win]
    - export OPENBLAS_NUM_THREADS=1       # [not win]
    - export OMP_NUM_THREADS=1            # [not win]
    - pytest --timeout 300 -n {{ test_cpus }} --verbose --pyargs sklearn -k "not ({{ tests_to_skip }})"

about:
  home: https://scikit-learn.org/
  license: BSD-3-Clause
  license_file: COPYING
  license_family: BSD
  summary: A set of python modules for machine learning and data mining
  description: |
    Scikit-learn is an open source machine learning library that supports supervised and unsupervised learning. 
    It also provides various tools for model fitting, data preprocessing, model selection, model evaluation, 
    and many other utilities.
  doc_url: https://scikit-learn.org/dev/user_guide.html
  dev_url: https://github.com/scikit-learn/scikit-learn

extra:
  recipe-maintainers:
    - amueller
    - astaric
    - jakirkham
    - ogrisel
    - ocefpaf
    - lesteve
    - jnothman
    - rth
    - adrinjalali
    - glemaitre
    - jeremiedbb
