{% set version = "0.19.0" %}

package:
  name: scikit-learn
  version: {{ version }}

source:
  url: https://github.com/scikit-learn/scikit-learn/archive/{{ version }}.tar.gz
  sha256: 25a889df32b9b3353f990726b54b6dc3e52a871ae8aea42e1f49d6726226f83c

build:
  number: 2
  # conda 4.4+ can use this
  requires_features:
    blas: {{ blas_impl }}
  # this is for conda 4.3 and below
  features:
    - nomkl    # [x86 and blas_impl != 'mkl']

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - setuptools
    - numpy
    - scipy
    - nose
    - mkl-devel  {{ mkl }}  # [blas_impl == 'mkl']
    - openblas    # [blas_impl == 'openblas']
  run:
    - python
    - scipy
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - nose
  imports:
    - sklearn
  commands:
    - nosetests sklearn --exe
    - conda inspect linkages -p $PREFIX scikit-learn  # [not win]
    - conda inspect objects -p $PREFIX scikit-learn  # [osx]

about:
  home: http://scikit-learn.org/
  license: BSD 3-Clause
  license_file: COPYING
  summary: A set of python modules for machine learning and data mining

extra:
  recipe-maintainers:
    - amueller
    - astaric
    - jakirkham
    - ogrisel
    - ocefpaf
    - lesteve
