{% set version = "0.19.2" %}
{% set name = "scikit-learn" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b276739a5f863ccacb61999a3067d0895ee291c95502929b2ae56ea1f882e888
  patches:
    - 0001-FIX-n_iter_-should-be-less-than-max_iter-in-when-usi.patch
    - atol_in_gaussian_tests.patch  # [win]
    - 0001-disable-test_predict_proba_binary.patch  # [win and vc==9]
    - 0001-FIX-cython-cluster-module-name-error-10343.patch

build:
  number: 0
  script: pip install -vvv .
  skip: True  # [blas_impl == 'openblas' and win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - cython
    - setuptools
    - numpy
    - scipy
    - nose
    - mkl-devel  {{ mkl }}  # [blas_impl == 'mkl']
    - openblas-devel {{ openblas }}  # [blas_impl == 'openblas']
    - nomkl  # [x86 and blas_impl == 'openblas']
  run:
    - python
    - scipy
    - {{ pin_compatible('numpy') }}

# TODO :: Fix this properly.
# Running into the same suspected i686 MKL bug that afflicts numpy and scipy
# (it is a shame to disable all tests for a few bad eggs, and, atol=0, really?):
# test_common.py.test_non_meta_estimators:check_supervised_y_2d(GaussianProcessRegressor)
# site-packages/numpy/testing/utils.py", line 778, in assert_array_compare
#     raise AssertionError(msg)
# AssertionError:
# Not equal to tolerance rtol=1e-07, atol=0
#
# (mismatch 30.0%)
#  x: array([ -4.066801e-08,   1.000000e+00,   2.000000e+00,   4.349049e-08,
#          1.000000e+00,   2.000000e+00,   1.880388e-08,   1.000000e+00,
#          2.000000e+00,   3.421711e-09])
#  y: array([ -4.066806e-08,   1.000000e+00,   2.000000e+00,   4.349050e-08,
#          1.000000e+00,   2.000000e+00,   1.880386e-08,   1.000000e+00,
#          2.000000e+00,   3.421711e-09])
#
# ----------------------------------------------------------------------
# Ran 7994 tests in 367.589s
#
# FAILED (SKIP=77, failures=2)

test:
  requires:
    - nose
    - nomkl  # [x86_64 and blas_impl == 'openblas']
  imports:
    - sklearn
  commands:
    - nosetests sklearn --exe -v                      # [not linux32 and not ppc64le]
    - OMP_NUM_THREADS=1 nosetests sklearn --exe -v    # [ppc64le]

about:
  home: http://scikit-learn.org/
  license: BSD 3-Clause
  license_file: COPYING
  summary: A set of python modules for machine learning and data mining

extra:
  recipe-maintainers:
    - amueller
    - astaric
    - jakirkham
    - ogrisel
    - ocefpaf
    - lesteve
