{% set name = "scikit-learn" %}
{% set version = "1.7.0" %}
{% set sha256 = "c01e869b15aec88e2cdb73d27f15bdbe03bce8e2fb43afbe77c45d399e73a5a3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script_env:  # [win]
    - SCIKIT_LEARN_SHA256={{ sha256 }}  # [win]
  script:  # [not win]
    - {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-build-isolation . -vv  # [not win]
  missing_dso_whitelist:
    - '*/libc++.1.dylib'  # [osx]
    - '*/libomp.dylib'  # [osx]
  skip: True  # [py<310]
  #ignore_run_exports:
  #  - numpy

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - cython >=3.0.10,<3.2.0
    - numpy {{ numpy }}
    - llvm-openmp 14.0.6  # [osx]
    - scipy >=1.8.0,<1.16.0
    - meson-python >=0.16.0,<0.19.0
    - python-build  # [win]
  run:
    - python
    - joblib >=1.2.0
    - numpy >=1.22.0
    - scipy >=1.8.0      # [not (osx and x86_64)]
    # Build fails on osx-64 without the newest version of scipy.
    # https://github.com/scikit-learn/scikit-learn/issues/28367#issuecomment-1941101095
    - scipy >=1.13.0,<1.16.0  # [osx and x86_64]
    - threadpoolctl >=3.1.0
    - llvm-openmp  # [osx]
    - _openmp_mutex  # [linux]
  run_constrained:
    # mkl variant pulls in intel-openmp which conflicts with
    # llvm-openmp. i.e. force to use openblas variant of numpy, scipy,
    # etc.
    - blas=*=openblas  # [osx and x86_64]

test:
  downstreams:
    #- category_encoders 2.2.2 # scikit-learn >=0.20.0 - update
    #- category_encoders 2.8.0 # scikit-learn >=1.6.0 - update
    #- prince 0.13.0 # scikit-learn >=1.0.2,<2.0.0 - update

    #- dash-bio 0.2.0 # scikit-learn >=0.20.1 - retest
    #- dask-glm 0.2.0 # scikit-learn >=0.18 - retest
    #- dask-glm 0.3.2 # scikit-learn >=0.18 - retest

    # IMPOSSIBLE TO REBUILD (archive)
    #@@@@@@@@@@@@@@@@@
    # ImportError: cannot import name 'if_delegate_has_method' from 'sklearn.utils.metaestimators'
    #- dask-ml 1.9.0 # scikit-learn >=0.23.0 - retest
    # ++++++solution+++++++
    # - scikit-learn >=0.23.0,<1.4.0
    #@@@@@@@@@@@@@@@@@

    #@@@@@@@@@@@@@@@@@
    # ModuleNotFoundError: No module named 'pyarrow'
    - dask-ml 2025.1.0 # scikit-learn >=1.6.1 - retest
    # ++++++solution+++++++
    # need to add pyarrow in test requires for dask-ml
    #@@@@@@@@@@@@@@@@@

    #@@@@@@@@@@@@@@@@@
    # ImportError: cannot import name 'inf' from 'scipy'
    - esda 2.4.1 # scikit-learn scikit-learn - retest
    # ++++++solution+++++++
    # Scipy removed scipy.inf starting from 1.8
    #@@@@@@@@@@@@@@@@@

    #- esda 2.7.0 # scikit-learn >=1.2 - retest
    #- imbalanced-learn 0.13.0 # scikit-learn >=1.3.2,<2 - retest
    #- keras-tuner 1.4.7 # scikit-learn scikit-learn - retest
    #- kmodes 0.12.2 # scikit-learn >=0.22.0 - retest
    #- libpysal 4.13.0 # scikit-learn >=1.1 - retest

    #@@@@@@@@@@@@@@@@@
    # FAILED lime/tests/test_scikit_image.py::TestSegmentationAlgorithm::test_instanciate_segmentation_algorithm - TypeError: quickshift() got an unexpected keyword argument 'random_seed'
    - lime 0.2.0.1 # scikit-learn >=0.18 - retest
    # ++++++solution+++++++
    # need to disable test
    #@@@@@@@@@@@@@@@@@

    #- mapclassify 2.4.3 # scikit-learn scikit-learn - retest
    #- mapclassify 2.9.0 # scikit-learn >=1.4 - retest
    #- mlflow 2.18.0 # scikit-learn <2 - retest
    #- mlxtend 0.23.4 # scikit-learn >=1.3.1 - retest

    #@@@@@@@@@@@@@@@@@
    # AttributeError: `np.sctypes` was removed in the NumPy 2.0 release. Access dtypes explicitly instead.
    - openml 0.12.2 # scikit-learn >=0.18 - retest
    # ++++++solution+++++++
    # need to add upperbound for run numpy <2
    #@@@@@@@@@@@@@@@@@

    #- opentsne 1.0.2 # scikit-learn >=0.20 - retest
    #- orange3 3.38.1 # scikit-learn >=1.5.1 - retest
    #- pmdarima 2.0.4 # scikit-learn >=0.22 - retest

    # impossible to rebuild (archive)
    #@@@@@@@@@@@@@@@@@
    # configparser.NoSectionError: No section: 'blas'
    # and
    # KeyError: 'blas__ldflags'
    #- pymc-experimental 0.0.9 # scikit-learn scikit-learn - retest
    #@@@@@@@@@@@@@@@@@

    # AttributeError: `np.infty` was removed in the NumPy 2.0 release. Use `np.inf` instead.
    #- pynndescent 0.5.4 # scikit-learn >=0.18 - retest
    # ++++++solution+++++++
    # need to add upperbound for run numpy <2

    # AttributeError: `np.infty` was removed in the NumPy 2.0 release. Use `np.inf` instead.
    #- pynndescent 0.5.10 # scikit-learn >=0.18 - retest
    # ++++++solution+++++++
    # need to add upperbound for run numpy <2

    #+- pyod 1.1.3 # scikit-learn >=0.22.0 - retest
    #+- pyts 0.12.0 # scikit-learn >=0.22.1 - retest
    #+- scikit-bio 0.5.6 # scikit-learn >=0.19.1 - retest

    # very long tests (passed locally)
    #- segregation 1.3.0 # scikit-learn scikit-learn - retest

    #- shap 0.47.2 # scikit-learn scikit-learn - retest
    #- skl2onnx 1.16.0 # scikit-learn >=0.19 - retest
    #- tbats 1.1.3 # scikit-learn scikit-learn - retest
    #- treeinterpreter 0.2.3 # scikit-learn >=0.17 - retest
    #- tsfresh 0.18.0 # scikit-learn >=0.22.0 - retest

    # >   raise TypeError(msg % type(expected_warning))
    # E   TypeError: exceptions must be derived from Warning, not <class 'NoneType'>
    #- umap-learn 0.5.4 # scikit-learn >=0.22 - retest
    # ++++++solution+++++++
    # ignore umap/tests/test_umap_ops.py tests
    # or
    # just skip

    # >   raise ReadError(f"file could not be opened successfully:\n{error_msgs_summary}")
    # E   tarfile.ReadError: file could not be opened successfully:
    # E   - method gz: ReadError('not a gzip file')
    # E   - method bz2: ReadError('not a bzip2 file')
    # E   - method xz: ReadError('not an lzma file')
    # E   - method tar: ReadError('bad checksum')
    #- woodwork 0.31.0 # scikit-learn >=1.1.0 - retest
    # ++++++solution+++++++
    # just skip

    #- yellowbrick 1.5 # scikit-learn >=1.0.0 - retest
  imports:
    - sklearn
    - sklearn.cluster
    - sklearn.compose
    - sklearn.covariance
    - sklearn.cross_decomposition
    - sklearn.datasets
    - sklearn.decomposition
    - sklearn.ensemble
    - sklearn.feature_extraction
    - sklearn.feature_selection
    - sklearn.frozen
    - sklearn.gaussian_process
    - sklearn.impute
    - sklearn.inspection
    - sklearn.linear_model
    - sklearn.manifold
    - sklearn.metrics
    - sklearn.mixture
    - sklearn.model_selection
    - sklearn.neighbors
    - sklearn.neural_network
    - sklearn.preprocessing
    - sklearn.semi_supervised
    - sklearn.svm
    - sklearn.tree
    - sklearn.utils
  commands:
    #- pip check
    - set OPENBLAS_NUM_THREADS=1  # [win]
    - set OMP_NUM_THREADS=1  # [win]
    - export OPENBLAS_NUM_THREADS=1  # [not win]
    - export OMP_NUM_THREADS=1  # [not win]
    # test_docstring
    # >   return ".".join([self.obj.__module__, self.obj.__name__])
    # E   AttributeError: 'property' object has no attribute '__module__'. Did you mean: '__reduce__'?
    #- pytest --timeout 1200 -nauto --verbose --pyargs sklearn -k "not (test_docstring)"
  requires:
    - pip
    - pytest >=7.1.2
    - pytest-timeout
    - pytest-xdist
    - matplotlib-base >=3.5.0
    - scikit-image >=0.17.2
    - pandas >=1.4.0
    # No polars
    #- polars >=0.20.23
    - pyarrow >=12.0.0
    # recent numpydoc not yet available
    - numpydoc >=1.2.0  # [py<313]
    - pooch >=1.6.0

about:
  home: https://scikit-learn.org
  license: BSD-3-Clause
  license_file: COPYING
  license_family: BSD
  summary: A set of python modules for machine learning and data mining
  description: |
    Scikit-learn is an open source machine learning library that
    supports supervised and unsupervised learning.  It also provides
    various tools for model fitting, data preprocessing, model
    selection, model evaluation, and many other utilities.
  doc_url: https://scikit-learn.org/dev/user_guide.html
  dev_url: https://github.com/scikit-learn/scikit-learn

extra:
  recipe-maintainers:
    - amueller
    - astaric
    - jakirkham
    - ogrisel
    - ocefpaf
    - lesteve
    - jnothman
    - rth
    - adrinjalali
    - glemaitre
    - jeremiedbb
