{% set version = "0.19.0" %}

package:
  name: scikit-learn
  version: {{ version }}

source:
  url: https://github.com/scikit-learn/scikit-learn/archive/{{ version }}.tar.gz
  sha256: 25a889df32b9b3353f990726b54b6dc3e52a871ae8aea42e1f49d6726226f83c

build:
  number: 2
  # conda 4.4+ can use this
  requires_features:
    blas: {{ blas_impl }}
  # this is for conda 4.3 and below
  features:
    - nomkl    # [x86 and blas_impl != 'mkl']

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - cython
    - setuptools
    - numpy
    - scipy
    - nose
    - mkl-devel  {{ mkl }}  # [blas_impl == 'mkl']
    - openblas    # [blas_impl == 'openblas']
  run:
    - python
    - scipy
    - {{ pin_compatible('numpy') }}

# TODO :: Fix this properly.
# Running into the same suspected i686 MKL bug that afflicts numpy and scipy
# (it is a shame to disable all tests for a few bad eggs, and, atol=0, really?):
# test_common.py.test_non_meta_estimators:check_supervised_y_2d(GaussianProcessRegressor)
# site-packages/numpy/testing/utils.py", line 778, in assert_array_compare
#     raise AssertionError(msg)
# AssertionError:
# Not equal to tolerance rtol=1e-07, atol=0
#
# (mismatch 30.0%)
#  x: array([ -4.066801e-08,   1.000000e+00,   2.000000e+00,   4.349049e-08,
#          1.000000e+00,   2.000000e+00,   1.880388e-08,   1.000000e+00,
#          2.000000e+00,   3.421711e-09])
#  y: array([ -4.066806e-08,   1.000000e+00,   2.000000e+00,   4.349050e-08,
#          1.000000e+00,   2.000000e+00,   1.880386e-08,   1.000000e+00,
#          2.000000e+00,   3.421711e-09])
#
# ----------------------------------------------------------------------
# Ran 7994 tests in 367.589s
#
# FAILED (SKIP=77, failures=2)

test:
  requires:                                           # [not linux32]
    - nose                                            # [not linux32]
  imports:
    - sklearn
  commands:
    - nosetests sklearn --exe                         # [not linux32]
    - conda inspect linkages -p $PREFIX scikit-learn  # [not win]
    - conda inspect objects -p $PREFIX scikit-learn   # [osx]

about:
  home: http://scikit-learn.org/
  license: BSD 3-Clause
  license_file: COPYING
  summary: A set of python modules for machine learning and data mining

extra:
  recipe-maintainers:
    - amueller
    - astaric
    - jakirkham
    - ogrisel
    - ocefpaf
    - lesteve
