{% set name = "scikit-learn" %}
{% set version = "1.9.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 8833266989d3a5110178a9fae30783675460724d0e1efb13b14901d2c660c557

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-build-isolation . -vv
  skip: true  # [py<311]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - cython >=3.1.2,<3.3.0
    - numpy {{ numpy }}
    - llvm-openmp {{ cxx_compiler_version }}  # [osx]
    - libgomp  # [linux]
    - vcomp14  # [win and x86_64]
    - scipy >=1.10.0,<1.18.0
    - meson-python >=0.17.1,<0.20.0
    - ninja-base
    - python-build  # [win]
  run:
    - python
    - numpy >=1.24.1
    - scipy >=1.10.0
    - joblib >=1.4.0
    - narwhals >=2.0.1
    - threadpoolctl >=3.5.0
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - vcomp14  # [win and x86_64]

test:
  imports:
    - sklearn
    - sklearn.cluster
    - sklearn.compose
    - sklearn.covariance
    - sklearn.cross_decomposition
    - sklearn.datasets
    - sklearn.decomposition
    - sklearn.ensemble
    - sklearn.feature_extraction
    - sklearn.feature_selection
    - sklearn.frozen
    - sklearn.gaussian_process
    - sklearn.impute
    - sklearn.inspection
    - sklearn.linear_model
    - sklearn.manifold
    - sklearn.metrics
    - sklearn.mixture
    - sklearn.model_selection
    - sklearn.neighbors
    - sklearn.neural_network
    - sklearn.preprocessing
    - sklearn.semi_supervised
    - sklearn.svm
    - sklearn.tree
    - sklearn.utils
  commands:
    - pip check
    - set OPENBLAS_NUM_THREADS=1  # [win]
    - set OMP_NUM_THREADS=1  # [win]
    - export OPENBLAS_NUM_THREADS=1  # [not win]
    - export OMP_NUM_THREADS=1  # [not win]
    - pytest --timeout 1200 -nauto --verbose --pyargs sklearn
  requires:
    - pip
    - matplotlib-base >=3.6.1
    - pandas >=1.5.0
    - pytest >=7.1.2
    - pytest-timeout
    - pytest-xdist
    - scikit-image >=0.22
    # Latest polars available for py313
    - polars >=0.20.30
    - pyarrow >=13.0.0
    # tests docstring failed with numpydoc >=1.9.0
    - numpydoc >=1.2.0,<1.9.0  # [py<313]
    - pooch >=1.8.0

about:
  home: https://scikit-learn.org
  license: BSD-3-Clause
  license_file: COPYING
  license_family: BSD
  summary: A set of python modules for machine learning and data mining
  description: |
    Scikit-learn is an open source machine learning library that
    supports supervised and unsupervised learning.  It also provides
    various tools for model fitting, data preprocessing, model
    selection, model evaluation, and many other utilities.
  doc_url: https://scikit-learn.org/dev/user_guide.html
  dev_url: https://github.com/scikit-learn/scikit-learn

extra:
  recipe-maintainers:
    - amueller
    - astaric
    - jakirkham
    - ogrisel
    - ocefpaf
    - lesteve
    - jnothman
    - rth
    - adrinjalali
    - glemaitre
    - jeremiedbb
