{% set version = "0.20.1" %}
{% set name = "scikit-learn" %}
{% set variant = "openblas" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: 0.20.1.tar.gz
  url: https://github.com/scikit-learn/scikit-learn/archive/0.20.1.zip
  sha256: 63c5099bfc7b4d849c36d3434b9b67233a75978c23dc32a9eb46f06704cc9cfe

build:
  number: 1200
  # We lack scipy on Windows, and therefore can't build numpy there either currently.
  skip: true  # [win]
  features:
    - blas_{{ variant }}
  script: python -m pip install --no-deps --ignore-installed .  --verbose

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - cython
    - setuptools
    - blas 1.1 {{ variant }}
    - openblas
    - numpy
    - scipy
    - pytest
  run:
    - python
    - blas 1.1 {{ variant }}
    - openblas
    - {{ pin_compatible('numpy') }}
    - scipy

test:
  requires:
    - pytest
  imports:
    - sklearn
  commands:
    - OPENBLAS_NUM_THREADS=2 pytest --pyargs sklearn

about:
  home: http://scikit-learn.org/
  license: BSD 3-Clause
  license_file: COPYING
  summary: A set of python modules for machine learning and data mining

extra:
  recipe-maintainers:
    - amueller
    - astaric
    - jakirkham
    - ogrisel
    - ocefpaf
    - lesteve
