{% set version = "0.21.1" %}

package:
  name: scikit-learn
  version: {{ version }}

source:
  url: https://github.com/scikit-learn/scikit-learn/archive/{{ version }}.tar.gz
  sha256: 7faa4c58336c83a449e1cc66eb2a08353821f492299263d03e7d2ddee27b6056
  patches:
    - 0001-disable-test_predict_proba_binary.patch    # [win]
    # https://github.com/scikit-learn/scikit-learn/issues/12676
    - 0002-xfail-test_omp_cv-due-to-mkl-issues.patch
    - 0003-add-a-few-atols-to-estimator-checks.patch  # [win]


build:
  number: 0
  skip: True  # [py2k]
  script:
    - "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
  host:
    - python
    - pip
    - llvm-openmp  # [osx]
    - cython >=0.28.5
    - mkl-devel  {{ mkl }}  # [blas_impl == 'mkl']
    - openblas-devel {{ openblas }}  # [blas_impl == 'openblas']
    - numpy-devel  {{ numpy }}
    - scipy >=0.17.0
    - joblib >=0.11
  run:
    - python
    - llvm-openmp  # [osx]
    - scipy
    - joblib >=0.11

test:
  requires:
    - pytest >=3.3.0
    - cython >=0.28.5
  imports:
    - sklearn
  commands:
    - set OPENBLAS_NUM_THREADS=1          # [win]
    - export OPENBLAS_NUM_THREADS=1       # [not win]
    - pytest --verbose --pyargs sklearn

about:
  home: http://scikit-learn.org/
  license: BSD 3-Clause
  license_file: COPYING
  summary: A set of python modules for machine learning and data mining

extra:
  recipe-maintainers:
    - amueller
    - astaric
    - jakirkham
    - ogrisel
    - ocefpaf
    - lesteve
    - jnothman
