{% set name = "scikit-learn" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 9bccbb3b40e3de10351f8f5068e105d0f4083b1a65fa07b6634fbc401a6287fd

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-build-isolation . -vv
  missing_dso_whitelist:
    - "*/libc++.1.dylib"  # [osx]
    - "*/libomp.dylib"  # [osx]
  skip: true  # [py<311]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - cython >=3.1.2,<3.3.0
    - numpy {{ numpy }}
    - llvm-openmp 14.0.6  # [osx]
    - scipy >=1.10.0,<1.17.0
    - meson-python >=0.17.1,<0.19.0
    - python-build  # [win]
    - numpy >=2,<2.4.0
  run:
    - python
    - joblib >=1.3.0
    - numpy >=1.24.1
    - scipy >=1.10.0
    - threadpoolctl >=3.2.0
    - llvm-openmp  # [osx]
    - _openmp_mutex  # [linux]
  run_constrained:
    # mkl variant pulls in intel-openmp which conflicts with
    # llvm-openmp. i.e. force to use openblas variant of numpy, scipy,
    # etc.
    - blas=*=openblas  # [osx and x86_64]
    - cython >=3.1.2
    - meson-python >=0.17.1
    - conda-lock ==3.0.1

test:
  imports:
    - sklearn
    - sklearn.cluster
    - sklearn.compose
    - sklearn.covariance
    - sklearn.cross_decomposition
    - sklearn.datasets
    - sklearn.decomposition
    - sklearn.ensemble
    - sklearn.feature_extraction
    - sklearn.feature_selection
    - sklearn.frozen
    - sklearn.gaussian_process
    - sklearn.impute
    - sklearn.inspection
    - sklearn.linear_model
    - sklearn.manifold
    - sklearn.metrics
    - sklearn.mixture
    - sklearn.model_selection
    - sklearn.neighbors
    - sklearn.neural_network
    - sklearn.preprocessing
    - sklearn.semi_supervised
    - sklearn.svm
    - sklearn.tree
    - sklearn.utils
  commands:
    - pip check
    - set OPENBLAS_NUM_THREADS=1  # [win]
    - set OMP_NUM_THREADS=1  # [win]
    - export OPENBLAS_NUM_THREADS=1  # [not win]
    - export OMP_NUM_THREADS=1  # [not win]
    - pytest --timeout 1200 -nauto --verbose --pyargs sklearn
  requires:
    - pip
    - pytest >=7.1.2
    - pytest-timeout
    - pytest-xdist
    - matplotlib-base >=3.5.0
    - scikit-image >=0.19
    - pandas >=1.4.0
    # latest polars in main = 0.20.18
    #- polars >=0.20.23
    # pyarrow is not available for python 3.14 on the main channel yet
    - pyarrow >=12.0.0  # [py<314]
    # tests docstring failed with numpydoc >=1.9.0
    - numpydoc >=1.2.0,<1.9.0  # [py<313]
    - pooch >=1.6.0

about:
  home: https://scikit-learn.org
  license: BSD-3-Clause
  license_file: COPYING
  license_family: BSD
  summary: A set of python modules for machine learning and data mining
  description: |
    Scikit-learn is an open source machine learning library that
    supports supervised and unsupervised learning.  It also provides
    various tools for model fitting, data preprocessing, model
    selection, model evaluation, and many other utilities.
  doc_url: https://scikit-learn.org/dev/user_guide.html
  dev_url: https://github.com/scikit-learn/scikit-learn

extra:
  recipe-maintainers:
    - amueller
    - astaric
    - jakirkham
    - ogrisel
    - ocefpaf
    - lesteve
    - jnothman
    - rth
    - adrinjalali
    - glemaitre
    - jeremiedbb
