{% set name = "scikit-learn" %}
{% set version = "1.7.0" %}
{% set sha256 = "c01e869b15aec88e2cdb73d27f15bdbe03bce8e2fb43afbe77c45d399e73a5a3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script_env:  # [win]
    - SCIKIT_LEARN_SHA256={{ sha256 }}  # [win]
  script:  # [not win]
    - {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-build-isolation . -vv  # [not win]
  missing_dso_whitelist:
    - '*/libc++.1.dylib'  # [osx]
    - '*/libomp.dylib'  # [osx]
  skip: True  # [py<310]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - cython >=3.0.10,<3.2.0
    - numpy {{ numpy }}
    - llvm-openmp 14.0.6  # [osx]
    - scipy >=1.8.0,<1.16.0
    - meson-python >=0.16.0,<0.19.0
    - python-build  # [win]
  run:
    - python
    - joblib >=1.2.0
    - numpy >=1.22.0
    - scipy >=1.8.0      # [not (osx and x86_64)]
    # Build fails on osx-64 without the newest version of scipy.
    # https://github.com/scikit-learn/scikit-learn/issues/28367#issuecomment-1941101095
    - scipy >=1.13.0,<1.16.0  # [osx and x86_64]
    - threadpoolctl >=3.1.0
    - llvm-openmp  # [osx]
    - _openmp_mutex  # [linux]
  run_constrained:
    # mkl variant pulls in intel-openmp which conflicts with
    # llvm-openmp. i.e. force to use openblas variant of numpy, scipy,
    # etc.
    - blas=*=openblas  # [osx and x86_64]

test:
  downstreams:
    - category_encoders 2.8.0 # scikit-learn >=1.6.0
    - dash-bio 0.2.0 # scikit-learn >=0.20.1
    # ImportError: cannot import name 'collections_to_dsk' from 'dask.base'
    #- dask-glm 0.3.2 # scikit-learn >=0.18
    # ModuleNotFoundError: No module named 'pyarrow'
    #- dask-ml 2025.1.0 # scikit-learn >=1.6.1
    - imbalanced-learn 0.13.0 # scikit-learn >=1.3.2,<2
    - kmodes 0.12.2 # scikit-learn >=0.22.0
    - libpysal 4.13.0 # scikit-learn >=1.1
    # lime/tests/test_scikit_image.py::TestSegmentationAlgorithm::test_instanciate_segmentation_algorithm - TypeError: quickshift() got an unexpected keyword argument 'random_seed'
    #- lime 0.2.0.1 # scikit-learn >=0.18
    - mapclassify 2.9.0 # scikit-learn >=1.4
    - mlflow 2.18.0 # scikit-learn <2
    - mlflow 2.0.1 # scikit-learn <2.0.0a0
    - mlxtend 0.23.4 # scikit-learn >=1.3.1
    - opentsne 1.0.2 # scikit-learn >=0.20
    - orange3 3.38.1 # scikit-learn >=1.5.1
    - pmdarima 2.0.4 # scikit-learn >=0.22
    #- prince 0.13.0 # scikit-learn >=1.0.2,<2.0.0
    # configparser.NoSectionError: No section: 'blas'
    #- pymc-experimental 0.0.9 # scikit-learn
    # AttributeError: `np.infty` was removed in the NumPy 2.0 release. Use `np.inf` instead.
    - pynndescent 0.5.10 # scikit-learn >=0.18
    - pyod 1.1.3 # scikit-learn >=0.22.0
    - pyts 0.12.0 # scikit-learn >=0.22.1
    - scikit-bio 0.5.6 # scikit-learn >=0.19.1
    - shap 0.47.2 # scikit-learn
    - skl2onnx 1.16.0 # scikit-learn >=0.19
    - snowflake-ml-python 1.0.2 # scikit-learn >=1.2.1,<2
    - tbats 1.1.3 # scikit-learn
    - treeinterpreter 0.2.3 # scikit-learn >=0.17
    # >   raise TypeError(msg % type(expected_warning))
    # E   TypeError: exceptions must be derived from Warning, not <class 'NoneType'>
    #- umap-learn 0.5.4 # scikit-learn >=0.22
    #>   raise ReadError(f"file could not be opened successfully:\n{error_msgs_summary}")
    #E   tarfile.ReadError: file could not be opened successfully:
    #E   - method gz: ReadError('not a gzip file')
    #E   - method bz2: ReadError('not a bzip2 file')
    #E   - method xz: ReadError('not an lzma file')
    #E   - method tar: ReadError('bad checksum')
    #- woodwork 0.31.0 # scikit-learn >=1.1.0
    - yellowbrick 1.5 # scikit-learn >=1.0.0
    - esda 2.7.0 # scikit-learn >=1.2
    - keras-tuner 1.4.7 # scikit-learn
    # AttributeError: `np.sctypes` was removed in the NumPy 2.0 release. Access dtypes explicitly instead.
    #- openml 0.12.2 # scikit-learn >=0.18
    - segregation 1.3.0 # scikit-learn
    - tsfresh 0.18.0 # scikit-learn >=0.22.0
    - scikit-optimize 0.9.0 # scikit-learn >=0.20.0
    - mlforecast 0.10.0 # scikit-learn
    - lightfm 1.17 # scikit-learn
    - fastai 2.7.18 # scikit-learn
    - scispacy 0.5.2 # scikit-learn >=0.20.3
    - scikit-learn-extra 0.3.0 # scikit-learn >=0.24.0
    - quantile-forest 1.1.2 # scikit-learn >=1.0
    - pycaret 3.0.2 # scikit-learn >=1.0
    - pycaret 3.3.2 # scikit-learn >1.4.0
    - sentence-transformers 3.4.1 # scikit-learn
    - evidently 0.4.39 # scikit-learn >=1.0.1
    - hdbscan 0.8.33 # scikit-learn >=0.20
    - pymc-marketing 0.1.1 # scikit-learn >=1.1.1
    - interpret-core 0.4.4 # scikit-learn >=0.18.1
    - recordlinkage 0.16 # scikit-learn >=1
    - bertopic 0.15.0 # scikit-learn >=0.22.2.post1
    - u8darts 0.33.0 # scikit-learn >=1.0.1
    - nlp_primitives 2.10.0 # scikit-learn >=0.20.0
    - feature_engine 1.6.2 # scikit-learn >=1.0.0
    - evalml 0.82.0 # scikit-learn >=1.3.0
    - seqeval 1.2.2 # scikit-learn >=0.21.3
    - pytorch-metric-learning 1.7.3 # scikit-learn
    - pytorch-tabnet 4.1.0 # scikit-learn >0.21
    - chainladder 0.8.23 # scikit-learn >=0.23
    - hierarchicalforecast 0.4.1 # scikit-learn
    - hmmlearn 0.3.2 # scikit-learn >=0.16,!=0.22.0
    - py_entitymatching 0.4.2 # scikit-learn >=0.22
    - imbalanced-ensemble 0.2.2 # scikit-learn >=1.5.0
    - dedupe 2.0.23 # scikit-learn
    - autoviml 0.1.800 # scikit-learn >=0.24
    - smac 1.2 # scikit-learn >=0.22.0
    - alibi-detect 0.11.4 # scikit-learn >=0.20.2,<2.0.0
    - data-science-utils 1.7.3 # scikit-learn >=1.2.2
    - trulens-feedback 1.1.0 # scikit-learn >=1.3.0,<2.0.0
    - autots 0.6.15 # scikit-learn >=0.20.0
    - lightweight-mmm 0.1.9 # scikit-learn
    - scikit-mobility 1.3.1 # scikit-learn
    - recbole 1.2.0 # scikit-learn >=0.23.2
    - flaml 1.2.4 # scikit-learn >=0.24
    - nannyml 0.12.1 # scikit-learn >=1.2,<2.0
    - scrubadub 2.0.1 # scikit-learn
    - metric-learn 0.7.0 # scikit-learn >=0.21.3,<1.3.2
    - tslearn 0.6.3 # scikit-learn
    - smote-variants 1.0.1 # scikit-learn
    - skrub 0.5.1 # scikit-learn >=1.2.1
    - scikit-llm 1.4.1 # scikit-learn >=1.1.0,<2.0.0
  imports:
    - sklearn
    - sklearn.cluster
    - sklearn.compose
    - sklearn.covariance
    - sklearn.cross_decomposition
    - sklearn.datasets
    - sklearn.decomposition
    - sklearn.ensemble
    - sklearn.feature_extraction
    - sklearn.feature_selection
    - sklearn.frozen
    - sklearn.gaussian_process
    - sklearn.impute
    - sklearn.inspection
    - sklearn.linear_model
    - sklearn.manifold
    - sklearn.metrics
    - sklearn.mixture
    - sklearn.model_selection
    - sklearn.neighbors
    - sklearn.neural_network
    - sklearn.preprocessing
    - sklearn.semi_supervised
    - sklearn.svm
    - sklearn.tree
    - sklearn.utils
  commands:
    - pip check
    - set OPENBLAS_NUM_THREADS=1  # [win]
    - set OMP_NUM_THREADS=1  # [win]
    - export OPENBLAS_NUM_THREADS=1  # [not win]
    - export OMP_NUM_THREADS=1  # [not win]
    # test_docstring
    # >   return ".".join([self.obj.__module__, self.obj.__name__])
    # E   AttributeError: 'property' object has no attribute '__module__'. Did you mean: '__reduce__'?
    - pytest --timeout 1200 -nauto --verbose --pyargs sklearn -k "not (test_docstring)"
  requires:
    - pip
    - pytest >=7.1.2
    - pytest-timeout
    - pytest-xdist
    - matplotlib-base >=3.5.0
    - scikit-image >=0.17.2
    - pandas >=1.4.0
    # No polars
    #- polars >=0.20.23
    - pyarrow >=12.0.0
    # recent numpydoc not yet available
    - numpydoc >=1.2.0  # [py<313]
    - pooch >=1.6.0

about:
  home: https://scikit-learn.org
  license: BSD-3-Clause
  license_file: COPYING
  license_family: BSD
  summary: A set of python modules for machine learning and data mining
  description: |
    Scikit-learn is an open source machine learning library that
    supports supervised and unsupervised learning.  It also provides
    various tools for model fitting, data preprocessing, model
    selection, model evaluation, and many other utilities.
  doc_url: https://scikit-learn.org/dev/user_guide.html
  dev_url: https://github.com/scikit-learn/scikit-learn

extra:
  recipe-maintainers:
    - amueller
    - astaric
    - jakirkham
    - ogrisel
    - ocefpaf
    - lesteve
    - jnothman
    - rth
    - adrinjalali
    - glemaitre
    - jeremiedbb
