{% set version = "1.1.3" %}

package:
  name: scikit-learn
  version: {{ version }}

source:
  url: https://github.com/scikit-learn/scikit-learn/archive/{{ version }}.tar.gz
  sha256: b7c0a9fb8dfcefcfc7ef8fe02a064d194980251d57efaea972cb76005afb3c63
  patches:
   - patches/sklearn-pr24141.patch
   - patches/sklearn-pr24483.patch
   - patches/sklearn-pr24543.patch

build:
  number: 0
  script: python -m pip install . --no-deps --no-build-isolation --ignore-installed -vv
  skip: true  # [py<38]
  missing_dso_whitelist:
    - '*/libc++.1.dylib'  # [osx]
    - '*/libomp.dylib'    # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - patch # [not win]
    - m2-patch # [win]
  host:
    - python
    - cython >=0.29.24
    - joblib >=1.0.0
    - llvm-openmp  # [osx]
    - numpy   1.19  # [py==38 or py==39]
    - numpy   1.21  # [py==310]
    - numpy   1.23  # [py>=311]
    - pip
    - scipy >=1.3.2,<=1.9.3 # [py<311]
    - scipy 1.10.0          # [py>=311]
    - setuptools <60.0
    - threadpoolctl >=2.0.0
    - wheel
  run:
    - python
    - joblib >=1.0.0
    - llvm-openmp  # [osx]
    - {{ pin_compatible('numpy') }}
    - scipy >=1.3.2,<=1.9.3 # [py<311]
    - scipy 1.10.0          # [py>=311]
    - threadpoolctl >=2.0.0
    - _openmp_mutex  # [linux]

# Some tests take alot of memory, and seem to cause segfaults when memory runs out
{% set test_cpus = 1 %}

{% set tests_to_skip = "_not_a_real_test" %}
# https://github.com/scikit-learn/scikit-learn/issues/20335
{% set tests_to_skip = tests_to_skip + " or test_loadings_converges" %}
# Numerically unstable test numerical difference in test
{% set tests_to_skip = tests_to_skip + " or test_mlp_regressor_dtypes_casting" %}         # [ppc64le]

test:
  requires:
    - pytest >=5.0.1
    - cython >=0.29.24
    - pytest-xdist
    - pytest-timeout
    - pip
  imports:
    - sklearn
  commands:
    - pip check
    - set OPENBLAS_NUM_THREADS=1          # [win]
    - set OMP_NUM_THREADS=1               # [win]
    - export OPENBLAS_NUM_THREADS=1       # [not win]
    - export OMP_NUM_THREADS=1            # [not win]
    - pytest --timeout 300 -n {{ test_cpus }} --verbose --pyargs sklearn -k "not ({{ tests_to_skip }})"

about:
  home: https://scikit-learn.org/
  license: BSD-3-Clause
  license_file: COPYING
  license_family: BSD
  license_url: https://github.com/scikit-learn/scikit-learn/blob/{{ version }}/COPYING
  summary: A set of python modules for machine learning and data mining
  description: |
    Scikit-learn is an open source machine learning library that supports supervised and unsupervised learning. 
    It also provides various tools for model fitting, data preprocessing, model selection, model evaluation, 
    and many other utilities.
  doc_url: https://scikit-learn.org/dev/user_guide.html
  dev_url: https://github.com/scikit-learn/scikit-learn
  doc_source_url: https://github.com/scikit-learn/scikit-learn/blob/{{ version }}/README.rst

extra:
  recipe-maintainers:
    - amueller
    - astaric
    - jakirkham
    - ogrisel
    - ocefpaf
    - lesteve
    - jnothman
    - rth
    - adrinjalali
    - glemaitre
    - jeremiedbb