{% set version = "1.1.1" %}

package:
  name: scikit-learn
  version: {{ version }}

source:
  url: https://github.com/scikit-learn/scikit-learn/archive/{{ version }}.tar.gz
  sha256: 568e621b9e1479b9ab952a9241db5af2ba3ab4f69d44b8aba3dd7648825e8e5a

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .  --verbose
  skip: true  # [py<38]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
  host:
    - python
    - cython >=0.29.24
    - joblib >=1.0.0
    - llvm-openmp  # [osx]
    - numpy
    - pip
    - scipy >=1.3.2
    - setuptools <60.0
    - threadpoolctl >=2.0.0
    - wheel
  run:
    - python
    - joblib >=1.0.0
    - llvm-openmp  # [osx]
    - {{ pin_compatible('numpy') }}
    - scipy >=1.3.2
    - threadpoolctl >=2.0.0
    - _openmp_mutex

# Some tests take alot of memory, and seem to cause segfaults when memory runs out
{% set test_cpus = 1 %}

{% set tests_to_skip = "_not_a_real_test" %}
# https://github.com/scikit-learn/scikit-learn/issues/20335
{% set tests_to_skip = tests_to_skip + " or test_loadings_converges" %}
# Numerically unstable test numerical difference in test
{% set tests_to_skip = tests_to_skip + " or test_mlp_regressor_dtypes_casting" %}         # [ppc64le]

test:
  requires:
    - pytest >=5.0.1
    - cython >=0.29.24
    - pytest-xdist
    - pytest-timeout
    - pip
  imports:
    - sklearn
  commands:
    - pip check
    - set OPENBLAS_NUM_THREADS=1          # [win]
    - set OMP_NUM_THREADS=1               # [win]
    - export OPENBLAS_NUM_THREADS=1       # [not win]
    - export OMP_NUM_THREADS=1            # [not win]
    - pytest --timeout 300 -n {{ test_cpus }} --verbose --pyargs sklearn -k "not ({{ tests_to_skip }})"

about:
  home: https://scikit-learn.org/
  license: BSD-3-Clause
  license_file: COPYING
  license_family: BSD
  summary: A set of python modules for machine learning and data mining
  doc_url: https://scikit-learn.org/dev/user_guide.html
  dev_url: https://github.com/scikit-learn/scikit-learn

extra:
  recipe-maintainers:
    - amueller
    - astaric
    - jakirkham
    - ogrisel
    - ocefpaf
    - lesteve
    - jnothman
    - rth
    - adrinjalali
    - glemaitre
    - jeremiedbb