{% set version = "0.21.0" %}
{% set variant = "openblas" %}

package:
  name: scikit-learn
  version: {{ version }}

source:
  url: https://github.com/scikit-learn/scikit-learn/archive/{{ version }}.tar.gz
  sha256: 15ff8f24909c68340532147ca6ff68e05508c836ceb5307c23d80a825a3e2a45

build:
  number: 0
  skip: True  # [py2k]
  script:
    - rm $PREFIX/include/cblas.h      # [not win]
    - del /f %LIBRARY_INC%\cblas.h    # [win]
    - export SKLEARN_NO_OPENMP=1  # [osx]
    # pip installing this fails randonly :-/
    - "{{ PYTHON }} setup.py install --single-version-externally-managed --record record.txt"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - libcblas
    - numpy 1.11.*
    - scipy >=0.17.0
    - joblib >=0.11
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - joblib >=0.11

test:
  requires:
    - pytest
    - cython
  imports:
    - sklearn
  commands:
    - set OPENBLAS_NUM_THREADS=1          # [win]
    - export OPENBLAS_NUM_THREADS=1       # [not win]
    - pytest --verbose --pyargs sklearn

about:
  home: http://scikit-learn.org/
  license: BSD 3-Clause
  license_file: COPYING
  summary: A set of python modules for machine learning and data mining

extra:
  recipe-maintainers:
    - amueller
    - astaric
    - jakirkham
    - ogrisel
    - ocefpaf
    - lesteve
    - jnothman
