travis:
  secure:
    BINSTAR_TOKEN: boWMIyP+oO6hQOUdzMvLEM+iWAEeUcWdjE66dg8cRummh7gX7t9E8+UpGydPA5VILqB8qHR94FHyS9eFYnYEoN3vM+HEoamWuWBp0Nk+IOrOFCcBQsImWP2drwujIhcWmO8sEuChQg+XcjRVWjSE3wWLaOMLLynWqB2PNv9cwIguLXApz1viOhYLqEgxjHYPSalPgUpdr0CPbtJ178WVDM2cO8Br2qo2FVHSM+pEsWzxIkpB879f85ozBZPz6yp25Kcxt/ctnTiPHbwc5O4NkCpoDvkNHlb2RtZG3FKs+8qTtm+I6BiyzPQuU0S1s+3eVGS/INzD7nzHlWzH+PpDD7XZCNlqLJb8a7fGfO36bNmAVyBhxTy/ZUcrko33YgiNk/P5hZU6xzN2uKSoTs5Muw9IUJxjXnxbSQgrS/HTYo4scG4To1oyfwRT5QtkZQ7bZu59YP2d11RL549NpaziwKUw1uuMSXCAZ24jwAtf/0vdyEq4Bi9P6BVKAz+pHqdLyWtzh8DuKPsv282q1ZumkSCCx9ewCMzYez6O3IjmxN3RmeJR5uUbQzkZGsOC/SvYsnwYj5AZP/cQ7xyyf3do5QAyb4nSXXMsK1eY2QUaFQ6VH3qjHFyXitA4MmQkRY3o/QbNzZf4zI+YKxKoIXSTqzeJNDGi1iJCnVqhTvDJ9Ho=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
